/* $Id:$ */
/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'PowerMessage'
 * message type.
 */

/*
 * mig java -java-classname=PowerMessage ../RadioControl.h PowerMessage -o PowerMessage.java
 */

package edu.clemson.cs.nestbed.server.nesc.comm.mig;


public class PowerMessage extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 1;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 17;

    /** Create a new PowerMessage of size 1. */
    public PowerMessage() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new PowerMessage of the given data_length. */
    public PowerMessage(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PowerMessage with the given data_length
     * and base offset.
     */
    public PowerMessage(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PowerMessage using the given byte array
     * as backing store.
     */
    public PowerMessage(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PowerMessage using the given byte array
     * as backing store, with the given base offset.
     */
    public PowerMessage(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PowerMessage using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public PowerMessage(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PowerMessage embedded in the given message
     * at the given base offset.
     */
    public PowerMessage(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PowerMessage embedded in the given message
     * at the given base offset and length.
     */
    public PowerMessage(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <PowerMessage> \n";
      try {
        s += "  [powerLevel=0x"+Long.toHexString(get_powerLevel())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: powerLevel
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'powerLevel' is signed (false).
     */
    public static boolean isSigned_powerLevel() {
        return false;
    }

    /**
     * Return whether the field 'powerLevel' is an array (false).
     */
    public static boolean isArray_powerLevel() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'powerLevel'
     */
    public static int offset_powerLevel() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'powerLevel'
     */
    public static int offsetBits_powerLevel() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'powerLevel'
     */
    public short get_powerLevel() {
        return (short)getUIntElement(offsetBits_powerLevel(), 8);
    }

    /**
     * Set the value of the field 'powerLevel'
     */
    public void set_powerLevel(short value) {
        setUIntElement(offsetBits_powerLevel(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'powerLevel'
     */
    public static int size_powerLevel() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'powerLevel'
     */
    public static int sizeBits_powerLevel() {
        return 8;
    }

}
