/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TraceMessage'
 * message type.
 */

public class TraceMessage extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 1;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 29;

    /** Create a new TraceMessage of size 1. */
    public TraceMessage() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TraceMessage of the given data_length. */
    public TraceMessage(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TraceMessage with the given data_length
     * and base offset.
     */
    public TraceMessage(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TraceMessage using the given byte array
     * as backing store.
     */
    public TraceMessage(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TraceMessage using the given byte array
     * as backing store, with the given base offset.
     */
    public TraceMessage(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TraceMessage using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TraceMessage(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TraceMessage embedded in the given message
     * at the given base offset.
     */
    public TraceMessage(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TraceMessage embedded in the given message
     * at the given base offset and length.
     */
    public TraceMessage(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TraceMessage> \n";
      try {
        s += "  [request=0x"+Long.toHexString(get_request())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: request
    //   Field type: byte, signed
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'request' is signed (true).
     */
    public static boolean isSigned_request() {
        return true;
    }

    /**
     * Return whether the field 'request' is an array (false).
     */
    public static boolean isArray_request() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'request'
     */
    public static int offset_request() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'request'
     */
    public static int offsetBits_request() {
        return 0;
    }

    /**
     * Return the value (as a byte) of the field 'request'
     */
    public byte get_request() {
        return (byte)getSIntBEElement(offsetBits_request(), 8);
    }

    /**
     * Set the value of the field 'request'
     */
    public void set_request(byte value) {
        setSIntBEElement(offsetBits_request(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'request'
     */
    public static int size_request() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'request'
     */
    public static int sizeBits_request() {
        return 8;
    }

}
